# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-28 09:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('editor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('subhead', models.CharField(max_length=20)),
                ('introduction', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=20)),
                ('create_time', models.DateTimeField()),
                ('last_change_time', models.DateTimeField()),
                ('content', models.TextField()),
                ('cover_page_photo_path', models.CharField(max_length=100)),
                ('like_num', models.IntegerField(default=0)),
                ('view_num', models.IntegerField(default=0)),
                ('is_headline', models.BooleanField(default='false')),
                ('editor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='editor', to='editor.Editor')),
                ('from_school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='editor.School')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_ip', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('create_time', models.DateTimeField()),
                ('floor', models.IntegerField()),
                ('like_num', models.IntegerField()),
                ('anonymous', models.BooleanField()),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article.Article')),
                ('author', models.ForeignKey(blank='true', null='true', on_delete=django.db.models.deletion.CASCADE, to='editor.Editor')),
                ('reply_for', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article.Comment')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Kind', models.CharField(choices=[('ADD', 'Add'), ('DEL', 'Delete'), ('UPD', 'Update'), ('CHK', 'Check')], max_length=3)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article.Article')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='editor.Editor')),
            ],
        ),
        migrations.CreateModel(
            name='Kind',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='LikeEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_ip', models.CharField(max_length=50)),
                ('post_time', models.DateTimeField()),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article.Article')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='editor.Editor')),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='kind',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article.Kind'),
        ),
        migrations.AddField(
            model_name='article',
            name='publisher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publisher', to='editor.Editor'),
        ),
    ]
